long call0( long);
long call1( long,long);
long call2( long,long,long);
long call3( long,long,long,long);
long call4( long,long,long,long,long);
long call5( long,long,long,long,long,long);
long call6( long,long,long,long,long,long,long);
long call7( long,long,long,long,long,long,long,long);
long call8( long,long,long,long,long,long,long,long,long);
long call9( long,long,long,long,long,long,long,long,long,long);
long call10(long,long,long,long,long,long,long,long,long,long,long);
long call11(long,long,long,long,long,long,long,long,long,long,long,long);
long call12(long,long,long,long,long,long,long,long,long,long,long,long,long);
long call13(long,long,long,long,long,long,long,long,long,long,long,long,long,long);
long call14(long,long,long,long,long,long,long,long,long,long,long,long,long,long,long);
long call15(long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long);

double doubleCall0( long);
double doubleCall1( long,long);
double doubleCall2( long,long,long);
double doubleCall3( long,long,long,long);
double doubleCall4( long,long,long,long,long);
double doubleCall5( long,long,long,long,long,long);
double doubleCall6( long,long,long,long,long,long,long);
double doubleCall7( long,long,long,long,long,long,long,long);
double doubleCall8( long,long,long,long,long,long,long,long,long);
double doubleCall9( long,long,long,long,long,long,long,long,long,long);
double doubleCall10(long,long,long,long,long,long,long,long,long,long,long);
double doubleCall11(long,long,long,long,long,long,long,long,long,long,long,long);
double doubleCall12(long,long,long,long,long,long,long,long,long,long,long,long,long);
double doubleCall13(long,long,long,long,long,long,long,long,long,long,long,long,long,long);
double doubleCall14(long,long,long,long,long,long,long,long,long,long,long,long,long,long,long);
double doubleCall15(long,long,long,long,long,long,long,long,long,long,long,long,long,long,long,long);
