// Copyright (c) 2013 Tony Wilson. All rights reserved.
// See LICENCE file for permissions and restrictions.

/*
Register all entry-points in winmm.dll.

DLL entry-points are registered for use by the
API access functions of github.com/tHinqa/outside.

Note that all dll exported named entry-points are listed,
including those that are undocumented by the vendor.
*/
package winmm

import "github.com/tHinqa/outside"

func init() {
	outside.AddEPs("winmm.dll", false, EntryPoints)
	outside.AddEPs("winmm.dll", true, UnicodeEntryPoints)
}

//TODO(t): Check Ws with no A counterparts and vv

var EntryPoints = outside.EPs{
	"CloseDriver",
	"DefDriverProc",
	"DriverCallback",
	"DrvGetModuleHandle",
	"GetDriverModuleHandle",
	"MigrateAllDrivers",
	"MigrateSoundEvents",
	"NotifyCallbackData",
	"OpenDriver",
	"PlaySound",
	"PlaySoundA",
	"SendDriverMessage",
	"WOW32DriverCallback",
	"WOW32ResolveMultiMediaHandle",
	"WOWAppExit",
	"WinmmLogoff",
	"WinmmLogon",
	"_gfxLogoff@0",
	"_gfxLogon@4",
	"aux32Message",
	"auxGetDevCapsA",
	"auxGetNumDevs",
	"auxGetVolume",
	"auxOutMessage",
	"auxSetVolume",
	"gfxAddGfx",
	"gfxBatchChange",
	"gfxCreateGfxFactoriesList",
	"gfxCreateZoneFactoriesList",
	"gfxDestroyDeviceInterfaceList",
	"gfxEnumerateGfxs",
	"gfxModifyGfx",
	"gfxOpenGfx",
	"gfxRemoveGfx",
	"joy32Message",
	"joyConfigChanged",
	"joyGetDevCapsA",
	"joyGetNumDevs",
	"joyGetPos",
	"joyGetPosEx",
	"joyGetThreshold",
	"joyReleaseCapture",
	"joySetCapture",
	"joySetThreshold",
	"mci32Message",
	"mciDriverNotify",
	"mciDriverYield",
	"mciExecute",
	"mciFreeCommandResource",
	"mciGetCreatorTask",
	"mciGetDeviceIDA",
	"mciGetDeviceIDFromElementIDA",
	"mciGetDriverData",
	"mciGetErrorStringA",
	"mciGetYieldProc",
	"mciLoadCommandResource",
	"mciSendCommandA",
	"mciSendStringA",
	"mciSetDriverData",
	"mciSetYieldProc",
	"mid32Message",
	"midiConnect",
	"midiDisconnect",
	"midiInAddBuffer",
	"midiInClose",
	"midiInGetDevCapsA",
	"midiInGetErrorTextA",
	"midiInGetID",
	"midiInGetNumDevs",
	"midiInMessage",
	"midiInOpen",
	"midiInPrepareHeader",
	"midiInReset",
	"midiInStart",
	"midiInStop",
	"midiInUnprepareHeader",
	"midiOutCacheDrumPatches",
	"midiOutCachePatches",
	"midiOutClose",
	"midiOutGetDevCapsA",
	"midiOutGetErrorTextA",
	"midiOutGetID",
	"midiOutGetNumDevs",
	"midiOutGetVolume",
	"midiOutLongMsg",
	"midiOutMessage",
	"midiOutOpen",
	"midiOutPrepareHeader",
	"midiOutReset",
	"midiOutSetVolume",
	"midiOutShortMsg",
	"midiOutUnprepareHeader",
	"midiStreamClose",
	"midiStreamOpen",
	"midiStreamOut",
	"midiStreamPause",
	"midiStreamPosition",
	"midiStreamProperty",
	"midiStreamRestart",
	"midiStreamStop",
	"mixerClose",
	"mixerGetControlDetailsA",
	"mixerGetDevCapsA",
	"mixerGetID",
	"mixerGetLineControlsA",
	"mixerGetLineInfoA",
	"mixerGetNumDevs",
	"mixerMessage",
	"mixerOpen",
	"mixerSetControlDetails",
	"mmDrvInstall",
	"mmGetCurrentTask",
	"mmTaskBlock",
	"mmTaskCreate",
	"mmTaskSignal",
	"mmTaskYield",
	"mmioAdvance",
	"mmioAscend",
	"mmioClose",
	"mmioCreateChunk",
	"mmioDescend",
	"mmioFlush",
	"mmioGetInfo",
	"mmioInstallIOProcA",
	"mmioOpenA",
	"mmioRead",
	"mmioRenameA",
	"mmioSeek",
	"mmioSendMessage",
	"mmioSetBuffer",
	"mmioSetInfo",
	"mmioStringToFOURCCA",
	"mmioWrite",
	"mmsystemGetVersion",
	"mod32Message",
	"mxd32Message",
	"sndPlaySoundA",
	"tid32Message",
	"timeBeginPeriod",
	"timeEndPeriod",
	"timeGetDevCaps",
	"timeGetSystemTime",
	"timeGetTime",
	"timeKillEvent",
	"timeSetEvent",
	"waveInAddBuffer",
	"waveInClose",
	"waveInGetDevCapsA",
	"waveInGetErrorTextA",
	"waveInGetID",
	"waveInGetNumDevs",
	"waveInGetPosition",
	"waveInMessage",
	"waveInOpen",
	"waveInPrepareHeader",
	"waveInReset",
	"waveInStart",
	"waveInStop",
	"waveInUnprepareHeader",
	"waveOutBreakLoop",
	"waveOutClose",
	"waveOutGetDevCapsA",
	"waveOutGetErrorTextA",
	"waveOutGetID",
	"waveOutGetNumDevs",
	"waveOutGetPitch",
	"waveOutGetPlaybackRate",
	"waveOutGetPosition",
	"waveOutGetVolume",
	"waveOutMessage",
	"waveOutOpen",
	"waveOutPause",
	"waveOutPrepareHeader",
	"waveOutReset",
	"waveOutRestart",
	"waveOutSetPitch",
	"waveOutSetPlaybackRate",
	"waveOutSetVolume",
	"waveOutUnprepareHeader",
	"waveOutWrite",
	"wid32Message",
	"winmmDbgOut",
	"winmmSetDebugLevel",
	"wod32Message",
}

var UnicodeEntryPoints = outside.EPs{
	"PlaySoundW",
	"auxGetDevCapsW",
	"joyGetDevCapsW",
	"mciGetDeviceIDFromElementIDW",
	"mciGetDeviceIDW",
	"mciGetErrorStringW",
	"mciSendCommandW",
	"mciSendStringW",
	"midiInGetDevCapsW",
	"midiInGetErrorTextW",
	"midiOutGetDevCapsW",
	"midiOutGetErrorTextW",
	"mixerGetControlDetailsW",
	"mixerGetDevCapsW",
	"mixerGetLineControlsW",
	"mixerGetLineInfoW",
	"mmioInstallIOProcW",
	"mmioOpenW",
	"mmioRenameW",
	"mmioStringToFOURCCW",
	"sndPlaySoundW",
	"waveInGetDevCapsW",
	"waveInGetErrorTextW",
	"waveOutGetDevCapsW",
	"waveOutGetErrorTextW",
}
